//! Do not edit this file.
//!
//! It records which release of the repo you have. When we push an update, this
//! number goes up, and the autograder uses it to tell you that there is work
//! waiting for you upstream.
//!
//! If a test tells you this is out of date, run:
//!
//!     git fetch upstream
//!     git merge upstream/main
#![allow(dead_code)]

/// Bumped by every staged release. The Sep 21 push sets this to 2.
pub const STENCIL_VERSION: u32 = 1;
